[profile.default]
src = "src"
out = "out"
libs = ["libs"] # Update this line to include your libs path
remappings = [
  "@libs=./src/libs",
  "@openzeppelin=./node_modules/@openzeppelin",
  "@solady=./node_modules/@openzeppelin",
  "@astrolabs=./node_modules/@astrolabs",
  "@redstone-finance=./node_modules/@redstone-finance",
  "@solady=./node_modules/solady",
  "forge-std/=./libs/forge-std/src/",
] # Add this line if you use remappings for your libraries
via_ir = false
optimizer = false
# optimizer_runs = 0
# optimizer_steps = 0
optimizer_details = { yul = false, peephole = true, jumpdest_removal = true, order_literals = true, deduplicate = true, cse = true, constant_optimizer = true, yul_details = { stack_allocation = false, optimizer_steps = "dhfoDgvulfnTUtnIf" } }
solc = "0.8.22"
evm_version = "shanghai"
allow_paths = ["."]
ffi = false

[fmt]
single_line_statetement_blocks = "preserve"
multiline_func_header = "params_first"
override_spacing = false
line_length = 90
tab_width = 2
bracket_spacing = false
int_types = "long"
quote_style = "double"
number_underscore = "preserve"
wrap_comments = false
ignore = ["./node_modules/**/*.sol", "./src/abstract/ERC20.sol"]

[profile.dependencies]
forge-std = { git = "https://github.com/foundry-rs/forge-std.git", branch = "master" }
